# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 17:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
